sudo: required
services:
- docker
language: bash
addons:
  apt:
    packages:
      - qemu
      - qemu-user-static
      - qemu-user
      - binfmt-support
script:
# Copy qemu binary
- cp /usr/bin/qemu-arm-static .
# Build image
- docker build -t organizrtools/docker-organizr-v2:armhf .
# Push image
- docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" ${DOCKER_REGISTRY}
- docker push organizrtools/docker-organizr-v2:armhf
