sudo: required
services:
  - docker
language: bash
script:
  # Build image
  - docker build -t organizrtools/organizr-v2:php-fpm .
  # Test image
  - docker run organizrtools/organizr-v2:php-fpm nginx -v
after_success:
  # Push image
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" ${DOCKER_REGISTRY}
  - docker push organizrtools/organizr-v2:php-fpm
